FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime as build

EXPOSE 7865

WORKDIR /app

RUN apt-get update && apt-get install -y \
    gcc \
    g++

COPY requirements.txt requirements.txt
RUN pip3 install -r requirements.txt

COPY . .

CMD ["python3", "-u", "infer-web.py"]